[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NEXT_PUBLIC_MEDUSA_BACKEND_URL = ""
  MEDUSA_BACKEND_URL = "http://165.227.197.59:9000"
  NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY = "pk_c2f5589f16eddc02305bfabd1ae20902c62bd43d2ef5ea7070310fd4f7f2b9e1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
